version: "3.8"

services:
  ray-head:
    build:
      context: ray
      dockerfile: Dockerfile
    user: root
    ports:
      - "8265:8265"
      - "10001:10001"
      - "8001:8000"
    volumes:
      - /tmp/ray:/tmp/ray  # Lưu dữ liệu Ray tại đây
    command: >
      bash -c "ray start --head
      --dashboard-port=8265
      --dashboard-host=0.0.0.0
      --port=6379
      --redis-password=your_password
      --block
      --temp-dir=/tmp/ray"
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://localhost:3009
      - RAY_PROMETHEUS_HOST=http://prometheus:9091
      - RAY_PROMETHEUS_NAME=Prometheus
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - confluent

  ray-worker:
    image: rayproject/ray:2.5.0-py39
    depends_on:
      - ray-head
    command: bash -c "ray start --address=ray-head:6379 --redis-password=your_password --num-cpus=2 --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    networks:
      - confluent

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /tmp/ray/session_latest/metrics/prometheus:/etc/prometheus  # Lưu dữ liệu Prometheus tại đây
    ports:
      - "9091:9090"
    networks:
      - confluent

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /tmp/ray/session_latest/metrics/grafana:/var/lib/grafana  # Lưu dữ liệu Grafana tại đây
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - confluent

networks:
  confluent:
    external: true