---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-minio.yml -o k8s/minio.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  type: NodePort
  selector:
    io.kompose.service: minio

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-minio.yml -o k8s/minio.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose-minio.yml -o k8s/minio.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
            - name: MINIO_ROOT_USER
              value: minioadmin
          image: minio/minio
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: minio
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
      hostname: minio
      restartPolicy: Always

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-minio.yml -o k8s/minio.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: minio-setup
  name: minio-setup
spec:
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose-minio.yml -o k8s/minio.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: minio-setup
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - |
              sleep 5;
              /usr/bin/mc config --quiet host add dmlminio http://minio:9000 minioadmin minioadmin;
              /usr/bin/mc ls dmlminio/bronze || /usr/bin/mc mb --quiet dmlminio/bronze;
              /usr/bin/mc ls dmlminio/storage || /usr/bin/mc mb --quiet dmlminio/storage;
              exit 0;
          env:
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
            - name: MINIO_ROOT_USER
              value: minioadmin
          image: minio/mc
          name: minio-setup
      restartPolicy: OnFailure
  backoffLimit: 3