{
 "title": "bigdata",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "disk flush requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_flush_requests_time_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_discarded_sectors_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk discard total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_discard_time_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu guest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "node_cpu_guest_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cooling device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "node_cooling_device_cur_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "context switches total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "node_context_switches_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "boot time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "arp entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "node_arp_entries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "latency seconds sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "inference_latency_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "latency bucket",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inference_latency_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency_count",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "inference_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}