# broker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      hostname: broker
      containers:
      - name: broker
        image: confluentinc/cp-server
        ports:
        - containerPort: 9092
        - containerPort: 9101
        - containerPort: 29092 
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092"
        # ... (thêm các biến môi trường khác tương tự)
        readinessProbe:
          exec:
            command: ["bash", "-c", "nc -z localhost 9092"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5

---
# broker-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  - name: kafka-external
    port: 29092
    targetPort: 29092   
  - name: jmx
    port: 9101
    targetPort: 9101
