# spark-master-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark:latest
        command: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
        ports:
        - containerPort: 8080
        - containerPort: 7077
        volumeMounts:
        - name: spark-app
          mountPath: "/opt/spark_app"
      volumes:
      - name: spark-app
        hostPath:
          path: ./spark_app

---
# spark-master-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: webui
    port: 9090
    targetPort: 8080
  - name: master
    port: 7077
    targetPort: 7077

# spark-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 1  # Có thể tăng số lượng worker nếu cần
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest
        command: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_WORKER_CORES
          value: "2"
        - name: SPARK_WORKER_MEMORY
          value: "1g"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        volumeMounts:
        - name: spark-app
          mountPath: "/opt/spark_app"
      volumes:
      - name: spark-app
        hostPath:
          path: ./spark_app