# zookeeper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        livenessProbe:  # Thay healthcheck bằng livenessProbe
          exec:
            command: ["bash", "-c", "echo 'ruok' | nc localhost 2181"]
          initialDelaySeconds: 10  # Tương đương với interval
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5  # Tương đương với retries

---
# zookeeper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181